### PR TITLE
Update CMakeLists.txt

### PR DESCRIPTION
**Pull request by wangzheallen**

### CODE REVIEW

**Comment by innerlee** [comment]
Generally speaking, static libs are not needed for installation because they are only useful when building.

Do you know why shipping static libs solve the previous issue?

**Comment by wangzheallen** [comment]
Not sure why it works, just search over stackoverflow and follow: https://stackoverflow.com/questions/14990343/cmake-error-targets-given-no-library-destination-for-shared-library-target
BTW, I also added PATH, C_INCLUDE_PATH, LD_LIBRARY_PATH whenever I compile some library to make files under app accessible.

**Comment by innerlee** [comment]
I guess it was the added paths who solved the problem. Let's hold this pr until the second one encounter with similar problem and verifies the fix :D

**Review by innerlee — APPROVED** [review]

**Comment by OpenMMLab-Assistant-004** [comment]
Hi @wangzheallen ！First of all, we want to express our gratitude for your significant PR in the denseflow project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/raweFPmdzG

If you are Chinese or have WeChat，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤

**Pull request merged**
